### ISSUE TITLE
local repo setup issue

### ISSUE THREAD

**Issue by jacobdonoghue** [heristop/gutenku#26]
Hi,

I've been following the instructions at https://github.com/heristop/gutenku/blob/main/packages/server/README.md, but when I run ```docker-compose up -d``` i get the following error: ```(root) Additional property mongo-container is not allowed```. When I edit the docker-compose.yaml file to include the services parameter, this goes away.
<img width="263" alt="Screen Shot 2023-06-04 at 10 22 25 AM" src="https://github.com/heristop/gutenku/assets/67441044/874cc4be-baaf-42e8-9add-a4997690c5e2">

However, now when I run docker-compose, it just gets hung up and doesn't spin up the mongo server. Any advice on how to troubleshoot/proceed?

**Comment by heristop** [comment]
Hello,

The config uses docker compose v1. I think it might explain your issue.

Regards

**Comment by heristop** [comment]
Fixed with #40
